const fs=require('fs');
const path=require('path');
const assert=require('assert');
const ts=require('typescript');

const root=path.resolve(__dirname,'..');
const read=relative=>fs.readFileSync(path.join(root,relative),'utf8');
const output=ts.transpileModule(read('src/lib/sms.ts'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const smsModule={exports:{}};
new Function('module','exports',output)(smsModule,smsModule.exports);
const {DEFAULT_SMS_TEMPLATES,normalizeSmsPhone,validateSmsTemplate,renderSmsTemplate}=smsModule.exports;
assert.strictEqual(normalizeSmsPhone('0771234567'),'+94771234567');
assert.strictEqual(normalizeSmsPhone('+94 77 123 4567'),'+94771234567');
assert.strictEqual(normalizeSmsPhone('123'),null);
for(const value of Object.values(DEFAULT_SMS_TEMPLATES))assert.strictEqual(validateSmsTemplate(value),'');
assert(validateSmsTemplate('Bad {unknown}').includes('Unsupported placeholder'));
assert(validateSmsTemplate('Emoji 🚨').includes('plain SMS'));
const rendered=renderSmsTemplate(DEFAULT_SMS_TEMPLATES.accident,{vehicleName:'Bus A',plateNumber:'AB 2345',eventType:'Accident',eventTime:'Now',impactG:'1.64',locationUrl:'Location unavailable'});
assert(rendered.includes('AB 2345')&&rendered.includes('1.64g')&&!rendered.includes('{'));
const independentlyEdited={...DEFAULT_SMS_TEMPLATES,accident:'Custom accident {plateNumber}'};
assert.strictEqual(independentlyEdited.drowsiness,DEFAULT_SMS_TEMPLATES.drowsiness);
assert.strictEqual(independentlyEdited.emergencyButton,DEFAULT_SMS_TEMPLATES.emergencyButton);

const contacts=read('src/screens/ContactsScreen.tsx');
const smsSource=read('src/lib/sms.ts');
for(const text of ['SMS Settings','Enable NORMAL SMS','Return to TEST ONLY','SMS Dispatch History','Send Test SMS'])assert(contacts.includes(text));
for(const text of ['Accident Detection SMS','Driver Drowsiness SMS','Mobile Emergency SMS','DEFAULT_SMS_MODE_CONFIG'])assert(smsSource.includes(text));
for(const field of ['smsEnabled','allowTestSms','notifyAccident','notifyDrowsiness','notifyEmergencyButton'])assert(contacts.includes(field));
for(const marker of ['contactFormOpen','toggle-emergency-contact-form','Tap to enter contact details','Tap to shrink this form','Cancel and collapse'])assert(contacts.includes(marker),`Missing collapsible contact marker: ${marker}`);
assert(contacts.includes('useState(false)')&&contacts.includes('setContactFormOpen(true)')&&contacts.includes('setContactFormOpen(false)'));
for(const marker of ['toggle-sms-mode','Collapse mode settings','expandedContactId','toggle-emergency-contact-${item.id}','Collapse contact','toggle-sms-template-${type}','Collapse template'])assert(contacts.includes(marker),`Missing collapsible SMS section marker: ${marker}`);
const database=read('src/lib/database.ts');
for(const pathName of ['smsSettingsPath','smsDispatchPath','smsTestRequests','watchSmsModeConfig','saveSmsModeConfig','watchSmsDispatchHistory'])assert(database.includes(pathName));
const rules=JSON.parse(read('database.rules.json')).rules;
assert(rules.smsSettings&&rules.smsTestRequests&&rules.smsDispatch);
assert.strictEqual(rules.smsSettings.$vehicleId.config.mode['.validate'],"newData.val() === 'test' || newData.val() === 'normal'");
assert(rules.smsSettings.$vehicleId.config['.validate'].includes('normalEnabledAt'));
assert.strictEqual(rules.smsDispatch.$vehicleId['.write'],false);
assert(rules.smsTestRequests.$vehicleId.$requestId['.write'].includes("allowTestSms').val() === true"));
assert.strictEqual(rules.deviceData.$vehicleId['.write'],false);
const firmware=read('hardware/FYP.ino');
for(const marker of ['CONFIG_READY','SMS_REQUEST:','SMS_RESULT:','EVENT:TEST_ACCIDENT','AT+CGPSINF=0'])assert(firmware.includes(marker));
for(const marker of ['SMS_MODE:','SMS_MODE_APPLIED:','NORMAL_MODE_REQUIRED','TEST_PREFIX_REQUIRED','INVALID_DISPATCH_MODE','normalSmsMode'])assert(firmware.includes(marker));
for(const missingInput of ['IR_PIN','EMERGENCY_BUTTON_PIN','checkDrowsiness(','checkEmergencyButton(','EVENT:DROWSINESS','EVENT:EMERGENCY_BUTTON'])assert(!firmware.includes(missingInput));
for(const mpuSetting of ['BUZZER_PIN = 8','MPU_ACCEL_CONFIG_REG = 0x1C','MPU_ACCEL_CONFIG_8G = 0x10','MPU_ACCEL_LSB_PER_G = 4096.0f','MPU_ACCEL_CONFIG_BEFORE:','MPU_ACCEL_CONFIG_AFTER:'])assert(firmware.includes(mpuSetting));
assert(!firmware.includes('/ 16384.0f'));
assert(!firmware.includes('+94778072817'));
console.log('PASS: owner SMS mode UI, activation rules, templates, contact opt-ins, history, and safe-default Arduino protocol.');
